### ISSUE TITLE
Read default version to go.mod version if present

### ISSUE THREAD

**Issue by stevenh** [bufbuild/buf-setup-action#154]
It would nice if the default version could be discovered from the repo's `go.mod` version if present in the same vane as [go-version-file for action/setup-go](https://github.com/search?q=repo%3Aactions%2Fsetup-go%20go-version-file&type=code)

```
steps:
  - uses: actions/checkout@v2
  # Installs version 1.26.0
  - uses: bufbuild/buf-setup-action@v1.26.0
    with:
      go-version-file: go.mod
```
