### ISSUE TITLE
1.29.0-1 causing issue during setup

### ISSUE THREAD

**Issue by vieux** [bufbuild/buf-setup-action#188]
From my github action:

```
Run bufbuild/buf-setup-action@v1
  with:
    buf_user: ***
    buf_api_token: ***
    github_token: ***
    version: 1.29.0-1
    buf_domain: buf.build
  env:
    GOPRIVATE: buf.build/gen/go
Setting up buf version "1.29.0-1"
Resolving the download URL for the current platform...
Error: Not Found - https://docs.github.com/rest/releases/releases#get-a-release-by-tag-name
```

@emcfarlane

**Comment by sicoyle** [comment]
I can confirm this is indeed an issue rn 😅

**Comment by emcfarlane** [comment]
Sorry for the issue! Lastest should be at 1.29.0 and we will add better testing for future release. Thanks for reporting. Please let me know if you have any issues.

**Comment by passichenko** [comment]
I'm still seeing this error. Our setup is:
```
      - uses: bufbuild/buf-setup-action@v1
        with:
          buf_user: ${{ secrets.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_API_TOKEN }}
          github_token: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
```
I'm not very familiar with github action versioning, but don't you need to cut a release? Or should we use some other tag?
